In [1]:
# Import our dependencies
import pandas as pd
import numpy as np
from functools import reduce

In [2]:
#  Import and read the input csv
g_ss_df = pd.read_csv('../../Clean_Data/Clean_CSV_Files/gov_systems-ss_systems-complete.csv', encoding='utf-8')
# Ensure the sss_depth column is small unsigned int type.
g_ss_df['sss_depth'] = g_ss_df['sss_depth'].astype(pd.Int8Dtype())
g_ss_df

,Country_Year,country,Year,government_type,sss_depth,system_type
0,Albania_1990,Albania,1990,parliamentary republic,2,"Universal medical benefits,Social insurance (c..."
1,Albania_1991,Albania,1991,parliamentary republic,2,"Universal medical benefits,Social insurance (c..."
2,Albania_1992,Albania,1992,parliamentary republic,2,"Universal medical benefits,Social insurance (c..."
3,Albania_1993,Albania,1993,parliamentary republic,2,"Universal medical benefits,Social insurance (c..."
4,Albania_1994,Albania,1994,parliamentary republic,2,"Universal medical benefits,Social insurance (c..."
...,...,...,...,...,...,...
6100,Zimbabwe_2018,Zimbabwe,2018,presidential republic,1,Employer-liability system (cash sickness and m...
6101,Zimbabwe_2019,Zimbabwe,2019,presidential republic,1,Employer-liability system (cash sickness and m...
6102,Zimbabwe_2020,Zimbabwe,2020,presidential republic,1,Employer-liability system (cash sickness and m...
6103,Zimbabwe_2021,Zimbabwe,2021,presidential republic,1,Employer-liability system (cash sickness and m...
6104,Zimbabwe_2022,Zimbabwe,2022,presidential republic,1,Employer-liability system (cash sickness and m...

In [3]:
#  Import and read the input csv
md_df = pd.read_csv('../../Clean_Data/Clean_CSV_Files/MD_per_10k.csv', encoding='utf-8')
md_df = md_df.drop(['Country','Year'], axis=1)
md_df

       Country_Year  MD per 10k
0      Albania_1990       13.71
1      Albania_1991       14.52
2      Albania_1992       15.93
3      Albania_1993       13.68
4      Albania_1994       12.85
...             ...         ...
6100  Zimbabwe_2018        2.01
6101  Zimbabwe_2019        1.95
6102  Zimbabwe_2020        1.89
6103  Zimbabwe_2021        1.89
6104  Zimbabwe_2022        1.89

[6105 rows x 2 columns]

In [4]:
#  Import and read the input csv
cap_he_df = pd.read_csv('../../Clean_Data/Clean_CSV_Files/World_Bank_Capital_HE-1990_2022.csv', encoding='utf-8')
cap_he_df

       Country_Year  Capital HE (% GDP)
0      Albania_1990            0.005188
1      Albania_1991            0.005188
2      Albania_1992            0.005188
3      Albania_1993            0.005188
4      Albania_1994            0.005188
...             ...                 ...
6100  Zimbabwe_2018            0.172716
6101  Zimbabwe_2019            1.526442
6102  Zimbabwe_2020            0.118737
6103  Zimbabwe_2021            0.118737
6104  Zimbabwe_2022            0.118737

[6105 rows x 2 columns]

In [5]:
#  Import and read the input csv
wbdi_df = pd.read_csv('../../Clean_Data/Clean_CSV_Files/world_bank_dev_indicators-1990_2022.csv', encoding='utf-8')

wbdi_df['Total Labor Force (M)'] = wbdi_df['Total Labor Force'] / 1000000
wbdi_df['Total Population (M)'] = wbdi_df['Total Population'] / 1000000
wbdi_df = wbdi_df.drop(['Total Labor Force','Total Population'], axis=1)

wbdi_df

,Country_Year,Electricity Access (% Pop),Avg. Rainfall (mm/yr),Current HE (% GDP),Current HE per capita (PPP Int'l $),Domestic general gov't HE (% GDP),Domestic general gov't HE per capita (PPP Int'l $),Domestic private HE per capita (PPP Int'l $),GDP growth per capita %,GDP per capita (PPP Int'l $),LEx years,Population Density (people per sq. km),Tobacco use (% adults),Alcohol Consumption per capita (liters),Total Labor Force (M),Total Population (M)
0,Albania_1990,100.000000,1485.0,5.944186,222.786533,2.765835,103.662764,115.435286,-11.187905,2549.746801,73.144,119.946788,35.0,6.57,1.374478,3.286542
1,Albania_1991,100.000000,1485.0,5.944186,222.786533,2.765835,103.662764,115.435286,-27.566821,1909.319160,73.378,119.225912,35.0,6.57,1.429833,3.266790
2,Albania_1992,100.000000,1485.0,5.944186,222.786533,2.765835,103.662764,115.435286,-6.622551,1823.503609,73.715,118.505073,35.0,6.57,1.438342,3.247039
3,Albania_1993,100.000000,1485.0,5.944186,222.786533,2.765835,103.662764,115.435286,10.229949,2057.692048,73.939,117.784197,35.0,6.57,1.413557,3.227287
4,Albania_1994,100.000000,1485.0,5.944186,222.786533,2.765835,103.662764,115.435286,8.969762,2290.143917,74.131,117.063358,35.0,6.57,1.391914,3.207536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6100,Zimbabwe_2018,45.400288,657.0,4.670418,180.091128,1.594279,61.475349,64.993823,2.909395,2457.309859,61.414,38.909614,12.1,4.67,5.770226,15.052184
6101,Zimbabwe_2019,46.682095,657.0,3.659765,132.068691,0.522077,18.839995,31.431890,-8.177320,2296.845429,61.292,39.691374,12.1,4.67,5.912685,15.354608
6102,Zimbabwe_2020,52.747667,657.0,3.425581,118.127063,0.756783,26.096745,26.263578,-9.670405,2101.804597,61.124,40.505793,11.7,4.67,6.008633,15.669666
6103,Zimbabwe_2021,48.979927,657.0,3.425581,118.127063,0.756783,26.096745,26.263578,6.271613,2333.973632,59.253,40.505793,11.7,4.67,6.200666,15.993524
6104,Zimbabwe_2022,48.979927,657.0,3.425581,118.127063,0.756783,26.096745,26.263578,1.328184,2530.645987,59.253,40.505793,11.7,4.67,6.400551,16.320537

In [6]:
#  Import and read the input csv
dcs_df = pd.read_csv('../../Clean_Data/Clean_CSV_Files/daily_calorie_supply.csv', encoding='utf-8')
dcs_df = dcs_df.drop(['Country','Year'], axis=1)
dcs_df

       Country_Year  Daily Caloric Supply
0      Albania_1990                2568.0
1      Albania_1991                2572.0
2      Albania_1992                2654.0
3      Albania_1993                2795.0
4      Albania_1994                2877.0
...             ...                   ...
6100  Zimbabwe_2018                1908.0
6101  Zimbabwe_2019                1908.0
6102  Zimbabwe_2020                1908.0
6103  Zimbabwe_2021                1908.0
6104  Zimbabwe_2022                1908.0

[6105 rows x 2 columns]

In [7]:
# Merge the helper DataFrame with the original data to ensure the data range is complete.
frames = [g_ss_df, dcs_df, cap_he_df, md_df, wbdi_df]
complete_df = reduce(lambda left,right: pd.merge(left,right,how='left',on='Country_Year'),frames)

# Sort by 'Country' and 'Year'.
complete_df = complete_df.sort_values(['Country_Year'], axis=0)

In [8]:
complete_df.columns

Index(['Country_Year', 'country', 'Year', 'government_type', 'sss_depth',
       'system_type', 'Daily Caloric Supply', 'Capital HE (% GDP)',
       'MD per 10k', 'Electricity Access (% Pop)', 'Avg. Rainfall (mm/yr)',
       'Current HE (% GDP)', 'Current HE per capita (PPP Int'l $)',
       'Domestic general gov't HE (% GDP)',
       'Domestic general gov't HE per capita (PPP Int'l $)',
       'Domestic private HE per capita (PPP Int'l $)',
       'GDP growth per capita %', 'GDP per capita (PPP Int'l $)', 'LEx years',
       'Population Density (people per sq. km)', 'Tobacco use (% adults)',
       'Alcohol Consumption per capita (liters)', 'Total Labor Force (M)',
       'Total Population (M)'],
      dtype='object')

In [9]:
# Rearrange the columns
complete_df = complete_df[['Country_Year','country','Year','government_type','sss_depth','system_type','Avg. Rainfall (mm/yr)','Population Density (people per sq. km)',
       'Total Population (M)','Total Labor Force (M)', 'LEx years','MD per 10k','Electricity Access (% Pop)','Current HE (% GDP)', "Current HE per capita (PPP Int'l $)", 'Capital HE (% GDP)',
       "Domestic general gov't HE (% GDP)","Domestic general gov't HE per capita (PPP Int'l $)","Domestic private HE per capita (PPP Int'l $)",
       'GDP growth per capita %',"GDP per capita (PPP Int'l $)",'Daily Caloric Supply','Tobacco use (% adults)','Alcohol Consumption per capita (liters)']]

In [10]:
# Update the column names for brevity and clarity
complete_df = complete_df.rename(columns={'country':'Country','government_type':'Gov Type','sss_depth':'SSS Depth','system_type':'SSS Type',
            'Population Density (people per sq. km)':'Pop Density (#/sq km)','MD per 10k':'Doctors (#/10k pop)','Avg. Rainfall (mm/yr)':'Avg Rainfall (mm/yr)',
            "Current HE per capita (PPP Int'l $)":'Current HE per capita (PPP Intl $)',"Domestic general gov't HE (% GDP)":'Domestic General Gov HE (% GDP)',
            "Domestic general gov't HE per capita (PPP Int'l $)":'Domestic General Gov HE per capita (PPP Intl $)',"Domestic private HE per capita (PPP Int'l $)":'Domestic Private HE per capita (PPP Intl $)',
            "GDP per capita (PPP Int'l $)":'GDP per capita (PPP Intl $)','Alcohol Consumption per capita (liters)':'Alcohol Use per capita (liters)'})

In [11]:
complete_df

,Country_Year,Country,Year,Gov Type,SSS Depth,SSS Type,Avg Rainfall (mm/yr),Pop Density (#/sq km),Total Population (M),Total Labor Force (M),...,Current HE per capita (PPP Intl $),Capital HE (% GDP),Domestic General Gov HE (% GDP),Domestic General Gov HE per capita (PPP Intl $),Domestic Private HE per capita (PPP Intl $),GDP growth per capita %,GDP per capita (PPP Intl $),Daily Caloric Supply,Tobacco use (% adults),Alcohol Use per capita (liters)
0,Albania_1990,Albania,1990,parliamentary republic,2,"Universal medical benefits,Social insurance (c...",1485.0,119.946788,3.286542,1.374478,...,222.786533,0.005188,2.765835,103.662764,115.435286,-11.187905,2549.746801,2568.0,35.0,6.57
1,Albania_1991,Albania,1991,parliamentary republic,2,"Universal medical benefits,Social insurance (c...",1485.0,119.225912,3.266790,1.429833,...,222.786533,0.005188,2.765835,103.662764,115.435286,-27.566821,1909.319160,2572.0,35.0,6.57
2,Albania_1992,Albania,1992,parliamentary republic,2,"Universal medical benefits,Social insurance (c...",1485.0,118.505073,3.247039,1.438342,...,222.786533,0.005188,2.765835,103.662764,115.435286,-6.622551,1823.503609,2654.0,35.0,6.57
3,Albania_1993,Albania,1993,parliamentary republic,2,"Universal medical benefits,Social insurance (c...",1485.0,117.784197,3.227287,1.413557,...,222.786533,0.005188,2.765835,103.662764,115.435286,10.229949,2057.692048,2795.0,35.0,6.57
4,Albania_1994,Albania,1994,parliamentary republic,2,"Universal medical benefits,Social insurance (c...",1485.0,117.063358,3.207536,1.391914,...,222.786533,0.005188,2.765835,103.662764,115.435286,8.969762,2290.143917,2877.0,35.0,6.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6100,Zimbabwe_2018,Zimbabwe,2018,presidential republic,1,Employer-liability system (cash sickness and m...,657.0,38.909614,15.052184,5.770226,...,180.091128,0.172716,1.594279,61.475349,64.993823,2.909395,2457.309859,1908.0,12.1,4.67
6101,Zimbabwe_2019,Zimbabwe,2019,presidential republic,1,Employer-liability system (cash sickness and m...,657.0,39.691374,15.354608,5.912685,...,132.068691,1.526442,0.522077,18.839995,31.431890,-8.177320,2296.845429,1908.0,12.1,4.67
6102,Zimbabwe_2020,Zimbabwe,2020,presidential republic,1,Employer-liability system (cash sickness and m...,657.0,40.505793,15.669666,6.008633,...,118.127063,0.118737,0.756783,26.096745,26.263578,-9.670405,2101.804597,1908.0,11.7,4.67
6103,Zimbabwe_2021,Zimbabwe,2021,presidential republic,1,Employer-liability system (cash sickness and m...,657.0,40.505793,15.993524,6.200666,...,118.127063,0.118737,0.756783,26.096745,26.263578,6.271613,2333.973632,1908.0,11.7,4.67
6104,Zimbabwe_2022,Zimbabwe,2022,presidential republic,1,Employer-liability system (cash sickness and m...,657.0,40.505793,16.320537,6.400551,...,118.127063,0.118737,0.756783,26.096745,26.263578,1.328184,2530.645987,1908.0,11.7,4.67

In [12]:
complete_df.isna().sum()

Country_Year                                       0
Country                                            0
Year                                               0
Gov Type                                           0
SSS Depth                                          0
SSS Type                                           0
Avg Rainfall (mm/yr)                               0
Pop Density (#/sq km)                              0
Total Population (M)                               0
Total Labor Force (M)                              0
LEx years                                          0
Doctors (#/10k pop)                                0
Electricity Access (% Pop)                         0
Current HE (% GDP)                                 0
Current HE per capita (PPP Intl $)                 0
Capital HE (% GDP)                                 0
Domestic General Gov HE (% GDP)                    0
Domestic General Gov HE per capita (PPP Intl $)    0
Domestic Private HE per capita (PPP Intl $)        0
GDP growth per capita %                            0
GDP per capita (PPP Intl $)                        0
Daily Caloric Supply                               0
Tobacco use (% adults)                             0
Alcohol Use per capita (liters)                    0
dtype: int64

In [13]:
complete_df.to_csv('../../Clean_Data/Load_Database/complete_data.csv', encoding='utf-8', index=False)